HarrowDeck/Models/ErrorViewModel.cs
using System;

namespace HarrowDeck.Models
{
    public class ErrorViewModel
    {
        public string RequestId { get; set; }

        public bool ShowRequestId => !string.IsNullOrEmpty(RequestId);
    }
}

HarrowDeck/Models/HarrowCard.cs
using System;
using System.Collections.Generic;
using System.Linq;
using System.Threading.Tasks;

namespace HarrowDeck.Models
{
    public class HarrowCard
    {
	    public string Name { get; set; }

	    public string Suite { get; set; }

	    public string Alignment { get; set; }

	    public string Description { get; set; }

		public string CardColor { get; set; }
    }
}

HarrowDeck/ViewModels/TraditionalHandViewModel.cs
using System;
using System.Collections.Generic;
using System.Linq;
using System.Threading.Tasks;
using HarrowDeck.Models;

namespace HarrowDeck.ViewModels
{
    public class TraditionalHandViewModel
    {
	    public Dictionary<string, HarrowCard> TraditionalSpread { get; set; }

	    public HarrowDeck.HarrowDeck FullDeck { get; set; }
    }
}

HarrowDeck/Controllers/HarrowDeckController.cs
using System;
using System.Collections.Generic;
using System.Linq;
using System.Threading.Tasks;
using HarrowDeck.HarrowDeck;
using HarrowDeck.Models;
using HarrowDeck.ViewModels;
using Microsoft.AspNetCore.Mvc;

// For more information on enabling MVC for empty projects, visit https://go.microsoft.com/fwlink/?LinkID=397860

namespace HarrowDeck.Controllers
{
    public class HarrowDeckController : Controller
    {
        [HttpGet]
        public IActionResult Index()
        {
	        var deck = new HarrowDeck.HarrowDeck();
            return View(deck.Deck);
        }

		[HttpGet]
	    public IActionResult Details(string name)
	    {
			var deck = new HarrowDeck.HarrowDeck().Deck;
		    return View(deck.Find(e => e.Name == name));
	    }

		[HttpGet]
	    public IActionResult TraditionalHand()
	    {
		    var deck = new HarrowDeck.HarrowDeck();
			var reading = new HarrowReading();
		    var spread = reading.TraditionalReading(deck);
		    var vm = new TraditionalHandViewModel();
		    vm.FullDeck = deck;
		    vm.TraditionalSpread = spread;

			return View(vm);
	    }

	    [HttpPost]
	    public IActionResult TraditionalHand(IEnumerable<string> keyValuePair)
	    {
		    var deck = new HarrowDeck.HarrowDeck();
		    var reading = new HarrowReading();

		    return View(reading.TraditionalReading(deck));
	    }

		public IActionResult Help()
	    {
		    return View();
	    }
    }
}

HarrowDeck/Views/HarrowDeck/Details.cshtml
@model HarrowCard
@{
    ViewData["Title"] = "Details";
}

<header id="header" style="margin-bottom: 50px">
	<a asp-controller="HarrowDeck" asp-action="Index"><strong>@Model.Name</strong></a>
</header>

<div>Alignment: @Model.Alignment</div>
<div>Suite: @Model.Suite</div>
<div>Description:</div>
<div>@Model.Description</div>
<div>@Model.Description</div>
<div>@Model.Description</div>

HarrowDeck/Views/HarrowDeck/Help.cshtml
@{
    ViewData["Title"] = "Help";
}

<h2>Help</h2>

HarrowDeck/Views/HarrowDeck/Index.cshtml
@model List<HarrowCard>
@{
	ViewData["Title"] = "Index";
}

<div class="header">
	<h1>Pathfinder Harrow Deck</h1>
</div>

<h2>Strength</h2>
<div class="container">
	<div class="row">
		@foreach (var item in Model.Where(e => e.Suite == "Strength"))
		{	
		<div class="col-md-4 h-30" style="margin-bottom: 10px">
			<a class="div-link" asp-controller="HarrowDeck" asp-action="Details" asp-route-name="@item.Name">
				<h3>@item.Name</h3>
				<hr style="margin-top: 5px; margin-bottom: 10px" />
				<h5 class="alignment">@item.Alignment</h5>
				<div class="description">
					@item.Description
				</div>
			</a>
		</div>
		}
	</div>
</div>

<h2>Dexterity</h2>
<div class="container">
	<div class="row">
		@foreach (var item in Model.Where(e => e.Suite == "Dexterity"))
		{	
			<div class="col-md-4 h-30" style="margin-bottom: 10px">
				<a class="div-link" asp-controller="HarrowDeck" asp-action="Details" asp-route-name="@item.Name">
					<h3>@item.Name</h3>
					<hr style="margin-top: 5px; margin-bottom: 10px" />
					<h5 class="alignment">@item.Alignment</h5>
					<div class="description">
						@item.Description
					</div>
				</a>
			</div>
		}
	</div>
</div>

<h2>Constitution</h2>
<div class="container">
	<div class="row">
		@foreach (var item in Model.Where(e => e.Suite == "Constitution"))
		{	
			<div class="col-md-4 h-30" style="margin-bottom: 10px">
				<a class="div-link" asp-controller="HarrowDeck" asp-action="Details" asp-route-name="@item.Name">
					<h3>@item.Name</h3>
					<hr style="margin-top: 5px; margin-bottom: 10px" />
					<h5 class="alignment">@item.Alignment</h5>
					<div class="description">
						@item.Description
					</div>
				</a>
			</div>
		}
	</div>
</div>

<h2>Intelligence</h2>
<div class="container">
	<div class="row">
		@foreach (var item in Model.Where(e => e.Suite == "Intelligence"))
		{	
			<div class="col-md-4 h-30" style="margin-bottom: 10px">
				<a class="div-link" asp-controller="HarrowDeck" asp-action="Details" asp-route-name="@item.Name">
					<h3>@item.Name</h3>
					<hr style="margin-top: 5px; margin-bottom: 10px" />
					<h5 class="alignment">@item.Alignment</h5>
					<div class="description">
						@item.Description
					</div>
				</a>
			</div>
		}
	</div>
</div>

<h2>Wisdom</h2>
<div class="container">
	<div class="row">
		@foreach (var item in Model.Where(e => e.Suite == "Wisdom"))
		{	
			<div class="col-md-4 h-30" style="margin-bottom: 10px">
				<a class="div-link" asp-controller="HarrowDeck" asp-action="Details" asp-route-name="@item.Name">
					<h3>@item.Name</h3>
					<hr style="margin-top: 5px; margin-bottom: 10px" />
					<h5 class="alignment">@item.Alignment</h5>
					<div  class="description">
						@item.Description
					</div>
				</a>
			</div>
		}
	</div>
</div>

<h2>Charisma</h2>
<div class="container">
	<div class="row">
		@foreach (var item in Model.Where(e => e.Suite == "Charisma"))
		{	
			<div class="col-md-4 h-30" style="margin-bottom: 10px">
				<a class="div-link" asp-controller="HarrowDeck" asp-action="Details" asp-route-name="@item.Name">
					<h3>@item.Name</h3>
					<hr style="margin-top: 5px; margin-bottom: 10px" />
					<h5 class="alignment">@item.Alignment</h5>
					<div class="description">
						@item.Description
					</div>
				</a>
			</div>
		}
	</div>
</div>

HarrowDeck/Views/HarrowDeck/TraditionalHand.cshtml
@model HarrowDeck.ViewModels.TraditionalHandViewModel
@{
	ViewData["Title"] = "TraditionalSpread";
	ViewData["NumCards"] = "9";
}

<div class="row">
	<div class="col-lg-3">
		<div class="container">@Html.Partial("_StackedDeck", Model)</div>
	</div>
	<div class="col-lg-9">
		<div class="header">
			<h1>Alignment Based Harrow Deck</h1>
		</div>
		<div class="container ">
			<div class="row">
				<div class="col-md-4 h-30" style="margin-bottom: 10px;">
					<div class="margin @Model.TraditionalSpread["Lawful Good"].CardColor">
						<a id="Lawful Good" class="div-link" asp-controller="HarrowDeck" asp-action="Details" asp-route-name="@Model.TraditionalSpread["Lawful Good"].Name">
							<h3>@Model.TraditionalSpread["Lawful Good"].Name</h3>
							<hr style="margin-top: 5px; margin-bottom: 10px"/>
							<h5 class="alignment">@Model.TraditionalSpread["Lawful Good"].Alignment</h5>
							<div class="description">
								@Model.TraditionalSpread["Lawful Good"].Description
							</div>
							<div class="normal-description" hidden>
								@Model.TraditionalSpread["Lawful Good"].Description
							</div>
							<div class="inverted-description" hidden>
								@Model.TraditionalSpread["Lawful Good"].Description
							</div>
						</a>
					</div>
				</div>
				<div class="col-md-4 h-30" style="margin-bottom: 10px;">
					<div class="margin @Model.TraditionalSpread["Neutral Good"].CardColor">
						<a id="Lawful Good" class="div-link " asp-controller="HarrowDeck" asp-action="Details" asp-route-name="@Model.TraditionalSpread["Neutral Good"].Name">
							<h3>@Model.TraditionalSpread["Neutral Good"].Name</h3>
							<hr style="margin-top: 5px; margin-bottom: 10px"/>
							<h5 class="alignment">@Model.TraditionalSpread["Neutral Good"].Alignment</h5>
							<div class="description">
								@Model.TraditionalSpread["Neutral Good"].Description
							</div>
							<div class="normal-description" hidden>
								@Model.TraditionalSpread["Neutral Good"].Description
							</div>
							<div class="inverted-description" hidden>
								@Model.TraditionalSpread["Neutral Good"].Description
							</div>
						</a>
					</div>
				</div>
				<div class="col-md-4 h-30" style="margin-bottom: 10px;">
					<div class="margin @Model.TraditionalSpread["Chaotic Good"].CardColor">
						<a id="Lawful Good" class="div-link " asp-controller="HarrowDeck" asp-action="Details" asp-route-name="@Model.TraditionalSpread["Chaotic Good"].Name">
							<h3>@Model.TraditionalSpread["Chaotic Good"].Name</h3>
							<hr style="margin-top: 5px; margin-bottom: 10px"/>
							<h5 class="alignment">@Model.TraditionalSpread["Chaotic Good"].Alignment</h5>
							<div class="description">
								@Model.TraditionalSpread["Chaotic Good"].Description
							</div>
							<div class="normal-description" hidden>
								@Model.TraditionalSpread["Chaotic Good"].Description
							</div>
							<div class="inverted-description" hidden>
								@Model.TraditionalSpread["Chaotic Good"].Description
							</div>
						</a>
					</div>
				</div>
			</div>
			<div class="row">
				<div class="col-md-4 h-30" style="margin-bottom: 10px;">
					<div class="margin @Model.TraditionalSpread["Lawful Neutral"].CardColor">
						<a id="Lawful Good" class="div-link " asp-controller="HarrowDeck" asp-action="Details" asp-route-name="@Model.TraditionalSpread["Lawful Neutral"].Name">
							<h3>@Model.TraditionalSpread["Lawful Neutral"].Name</h3>
							<hr style="margin-top: 5px; margin-bottom: 10px"/>
							<h5 class="alignment">@Model.TraditionalSpread["Lawful Neutral"].Alignment</h5>
							<div class="description">
								@Model.TraditionalSpread["Lawful Neutral"].Description
							</div>
							<div class="normal-description" hidden>
								@Model.TraditionalSpread["Lawful Neutral"].Description
							</div>
							<div class="normal-description" hidden>
								@Model.TraditionalSpread["Lawful Neutral"].Description
							</div>
						</a>
					</div>
				</div>
				<div class="col-md-4 h-30" style="margin-bottom: 10px;">
					<div class="margin @Model.TraditionalSpread["True Neutral"].CardColor">
						<a id="Lawful Good" class="div-link " asp-controller="HarrowDeck" asp-action="Details" asp-route-name="@Model.TraditionalSpread["True Neutral"].Name">
							<h3>@Model.TraditionalSpread["True Neutral"].Name</h3>
							<hr style="margin-top: 5px; margin-bottom: 10px"/>
							<h5 class="alignment">@Model.TraditionalSpread["True Neutral"].Alignment</h5>
							<div class="description">
								@Model.TraditionalSpread["True Neutral"].Description
							</div>
							<div class="normal-description" hidden>
								@Model.TraditionalSpread["True Neutral"].Description
							</div>
							<div class="normal-description" hidden>
								@Model.TraditionalSpread["True Neutral"].Description
							</div>
						</a>
					</div>
				</div>
				<div class="col-md-4 h-30" style="margin-bottom: 10px;">
					<div class="margin @Model.TraditionalSpread["Chaotic Neutral"].CardColor">
						<a id="Lawful Good" class="div-link " asp-controller="HarrowDeck" asp-action="Details" asp-route-name="@Model.TraditionalSpread["Chaotic Neutral"].Name">
							<h3>@Model.TraditionalSpread["Chaotic Neutral"].Name</h3>
							<hr style="margin-top: 5px; margin-bottom: 10px"/>
							<h5 class="alignment">@Model.TraditionalSpread["Chaotic Neutral"].Alignment</h5>
							<div class="description">
								@Model.TraditionalSpread["Chaotic Neutral"].Description
							</div>
							<div class="normal-description" hidden>
								@Model.TraditionalSpread["Chaotic Neutral"].Description
							</div>
							<div class="normal-description" hidden>
								@Model.TraditionalSpread["Chaotic Neutral"].Description
							</div>
						</a>
					</div>
				</div>
			</div>
			<div class="row">
				<div class="col-md-4 h-30" style="margin-bottom: 10px;">
					<div class="margin @Model.TraditionalSpread["Lawful Evil"].CardColor">
						<a id="Lawful Good" class="div-link " asp-controller="HarrowDeck" asp-action="Details" asp-route-name="@Model.TraditionalSpread["Lawful Evil"].Name">
							<h3>@Model.TraditionalSpread["Lawful Evil"].Name</h3>
							<hr style="margin-top: 5px; margin-bottom: 10px"/>
							<h5 class="alignment">@Model.TraditionalSpread["Lawful Evil"].Alignment</h5>
							<div class="description">
								@Model.TraditionalSpread["Lawful Evil"].Description
							</div>
							<div class="normal-description" hidden>
								@Model.TraditionalSpread["Lawful Evil"].Description
							</div>
							<div class="normal-description" hidden>
								@Model.TraditionalSpread["Lawful Evil"].Description
							</div>
						</a>
					</div>
				</div>
				<div class="col-md-4 h-30" style="margin-bottom: 10px;">
					<div class="margin @Model.TraditionalSpread["Neutral Evil"].CardColor">
						<a id="Lawful Good" class="div-link " asp-controller="HarrowDeck" asp-action="Details" asp-route-name="@Model.TraditionalSpread["Neutral Evil"].Name">
							<h3>@Model.TraditionalSpread["Neutral Evil"].Name</h3>
							<hr style="margin-top: 5px; margin-bottom: 10px"/>
							<h5 class="alignment">@Model.TraditionalSpread["Neutral Evil"].Alignment</h5>
							<div class="description">
								@Model.TraditionalSpread["Neutral Evil"].Description
							</div>
							<div class="normal-description" hidden>
								@Model.TraditionalSpread["Neutral Evil"].Description
							</div>
							<div class="normal-description" hidden>
								@Model.TraditionalSpread["Neutral Evil"].Description
							</div>
						</a>
					</div>
				</div>
				<div class="col-md-4 h-30" style="margin-bottom: 10px;">
					<div class="margin @Model.TraditionalSpread["Chaotic Evil"].CardColor">
						<a id="Lawful Good" class="div-link " asp-controller="HarrowDeck" asp-action="Details" asp-route-name="@Model.TraditionalSpread["Chaotic Evil"].Name">
							<h3>@Model.TraditionalSpread["Chaotic Evil"].Name</h3>
							<hr style="margin-top: 5px; margin-bottom: 10px"/>
							<h5 class="alignment">@Model.TraditionalSpread["Chaotic Evil"].Alignment</h5>
							<div class="description">
								@Model.TraditionalSpread["Chaotic Evil"].Description
							</div>
							<div class="normal-description" hidden>
								@Model.TraditionalSpread["Chaotic Evil"].Description
							</div>
							<div class="normal-description" hidden>
								@Model.TraditionalSpread["Chaotic Evil"].Description
							</div>
						</a>
					</div>
				</div>
			</div>
		</div>
	</div>
</div>

<script src="http://ajax.googleapis.com/ajax/libs/jquery/1.11.2/jquery.min.js"></script>

<script>
	var placeHolders = $('.place-holder');
	for (var i = 0; i < placeHolders.length; i++) {
		var place = placeHolders[i];
		var alignment = place.id;
		var card = $(alignment).find('.alignment');

		//var cardAlignment = card.innerHTML();

		if (i/2 > 4) {
			place.addClass("rightside");
		}
	}
</script>

HarrowDeck/Views/Shared/_Layout.cshtml
<!DOCTYPE html>
<html>
<head>
    <meta charset="utf-8" />
    <meta name="viewport" content="width=device-width, initial-scale=1.0" />
    <title>@ViewData["Title"] - HarrowDeck</title>

    <environment include="Development">
        <link rel="stylesheet" href="~/lib/bootstrap/dist/css/bootstrap.css" />
        <link rel="stylesheet" href="~/css/site.css" />
    </environment>
    <environment exclude="Development">
        <link rel="stylesheet" href="https://ajax.aspnetcdn.com/ajax/bootstrap/3.3.7/css/bootstrap.min.css"
              asp-fallback-href="~/lib/bootstrap/dist/css/bootstrap.min.css"
              asp-fallback-test-class="sr-only" asp-fallback-test-property="position" asp-fallback-test-value="absolute" />
        <link rel="stylesheet" href="~/css/site.min.css" asp-append-version="true" />
    </environment>
</head>
<body>
    <nav class="navbar navbar-inverse navbar-fixed-top">
        <div class="menu-container">
            <div class="navbar-header">
                <button type="button" class="navbar-toggle" data-toggle="collapse" data-target=".navbar-collapse">
                    <span class="sr-only">Toggle navigation</span>
                    <span class="icon-bar"></span>
                    <span class="icon-bar"></span>
                    <span class="icon-bar"></span>
                </button>
                <a asp-area="" asp-controller="HarrowDeck" asp-action="Index" class="navbar-brand">HarrowDeck</a>
            </div>
	        <div class="navbar-collapse collapse">
		        <ul class="nav navbar-nav navbar-left">
			        <li><a asp-area="" asp-controller="HarrowDeck" asp-action="TraditionalHand">Traditional Hand</a></li>
			        <li><a asp-area="" asp-controller="HarrowDeck" asp-action="Index">Reduced Hand</a></li>
		        </ul>
		        <ul class="nav navbar-nav navbar-right">
			        <li><a asp-area="" asp-controller="HarrowDeck" asp-action="Help">Help</a></li>
		        </ul>
	        </div>
        </div>
    </nav>
    <div class="body-content">
        @RenderBody()
        <hr />
        <footer>
            <p>&copy; 2018 - HarrowDeck</p>
        </footer>
    </div>

    <environment include="Development">
        <script src="~/lib/jquery/dist/jquery.js"></script>
        <script src="~/lib/bootstrap/dist/js/bootstrap.js"></script>
        <script src="~/js/site.js" asp-append-version="true"></script>
    </environment>
    <environment exclude="Development">
        <script src="https://ajax.aspnetcdn.com/ajax/jquery/jquery-2.2.0.min.js"
                asp-fallback-src="~/lib/jquery/dist/jquery.min.js"
                asp-fallback-test="window.jQuery"
                crossorigin="anonymous"
                integrity="sha384-K+ctZQ+LL8q6tP7I94W+qzQsfRV2a+AfHIi9k8z8l9ggpc8X+Ytst4yBo/hH+8Fk">
        </script>
        <script src="https://ajax.aspnetcdn.com/ajax/bootstrap/3.3.7/bootstrap.min.js"
                asp-fallback-src="~/lib/bootstrap/dist/js/bootstrap.min.js"
                asp-fallback-test="window.jQuery && window.jQuery.fn && window.jQuery.fn.modal"
                crossorigin="anonymous"
                integrity="sha384-Tc5IQib027qvyjSMfHjOMaLkfuWVxZxUPnCJA7l2mCWNIpG9mGCD8wGNIcPD7Txa">
        </script>
        <script src="~/js/site.min.js" asp-append-version="true"></script>
    </environment>

    @RenderSection("Scripts", required: false)
</body>
</html>

HarrowDeck/Views/Shared/_StackedDeck.cshtml
@model HarrowDeck.ViewModels.TraditionalHandViewModel
<div class="container block">
	<div class="header">
		<h3>Stack the Deck</h3>
	</div>
	<form class="stack-the-deck form-group" asp-controller="HarrowDeck" asp-action="TraditionalHand" method="post">
		<div id="card-1" class="card">
			<div class="row">
				<div class="col-md-3">
					<label>Alignment Position</label>
					<input type="text" name="alignment" class="form-control"/>
				</div>
			</div>
			<div class="row">
				<div class="col-md-3">
					<label>Card Name</label>
					<input type="text" name="alignment" class="form-control"/>
				</div>
			</div>
		</div>
		<div class="button-container">
			<div id="add-card" class="btn btn-primary">+</div>
			<input class="btn btn-success" type="submit" name="submit" />
		</div>
	</form>
</div>

<script src="https://ajax.googleapis.com/ajax/libs/jquery/3.3.1/jquery.min.js"></script>

<script>
	var numCards = 1;

	var label1 = document.createElement('label').setAttribute('innerHTML', 'Alignment Position');
	var input1 = document.createElement('input').setAttribute('type', 'text').setAttribute('name', 'alignment')
		.setAttribute('class', 'form-control');
	var col1 = document.createElement('div').setAttribute('class', 'col-md-3').append(label1).append(input1);
	var row1 = document.createElement('div').setAttribute('class', 'row').append(col1);
	var container = document.createElement('div').setAttribute('class', 'card').setAttribute('id', 'card' + numCards).append(row1);

	$("#add-card").click(function () {
		var newCard = document.createElement()
		$('card-' + numCards);
		numCards += 1;
	});
</script>